<?php

namespace ContainerLx1qqRb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D82J_M9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D82J.M9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D82J.M9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employeeRepository' => ['privates', 'App\\Repository\\EmployeeRepository', 'getEmployeeRepositoryService', true],
        ], [
            'employeeRepository' => 'App\\Repository\\EmployeeRepository',
        ]);
    }
}
