<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWOgJwnx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWOgJwnx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWOgJwnx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWOgJwnx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWOgJwnx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WOgJwnx',
    'container.build_id' => 'b63245bb',
    'container.build_time' => 1718139742,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWOgJwnx');
