<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container53XATtw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container53XATtw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container53XATtw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container53XATtw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container53XATtw\App_KernelDevDebugContainer([
    'container.build_hash' => '53XATtw',
    'container.build_id' => 'af8915d4',
    'container.build_time' => 1718204925,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container53XATtw');
